// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Onus.API.Data;

#nullable disable

namespace Onus.API.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251208093955_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Onus.API.Models.BlogPost", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Excerpt")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsPublished")
                        .HasColumnType("boolean");

                    b.Property<DateTime?>("PublishedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("BlogPosts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Author = "Admin",
                            Category = "Mutfak",
                            Content = "Detaylı blog içeriği buraya gelecek...",
                            CreatedDate = new DateTime(2025, 12, 8, 9, 39, 54, 92, DateTimeKind.Utc).AddTicks(8887),
                            Excerpt = "Mutfak tasarımında 2024 yılının en öne çıkan trendlerini keşfedin.",
                            ImageUrl = "https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=800&q=80",
                            IsPublished = true,
                            PublishedDate = new DateTime(2025, 12, 8, 9, 39, 54, 92, DateTimeKind.Utc).AddTicks(8884),
                            Title = "Modern Mutfak Tasarım Trendleri 2024"
                        });
                });

            modelBuilder.Entity("Onus.API.Models.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsRead")
                        .HasColumnType("boolean");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("Onus.API.Models.HeroSlide", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ButtonLink")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ButtonText")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Subtitle")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HeroSlides");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ButtonLink = "/projeler",
                            ButtonText = "Projelerimizi Keşfedin",
                            Description = "Özel tasarım mutfak ve banyo çözümleri ile hayallerinizdeki mekanları yaratıyoruz.",
                            ImageUrl = "https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=1920&q=80",
                            IsActive = true,
                            Order = 1,
                            Subtitle = "Ahşabın Ustası",
                            Title = "Doğanın Çırağı"
                        },
                        new
                        {
                            Id = 2,
                            ButtonLink = "/hakkimizda",
                            ButtonText = "Hakkımızda",
                            Description = "Yılların deneyimi ile ahşap işçiliğinde en üst düzey kaliteyi sunuyoruz.",
                            ImageUrl = "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?auto=format&fit=crop&w=1920&q=80",
                            IsActive = true,
                            Order = 2,
                            Subtitle = "Her Detayda Kalite",
                            Title = "El İşçiliğinde Mükemmellik"
                        },
                        new
                        {
                            Id = 3,
                            ButtonLink = "/iletisim",
                            ButtonText = "İletişime Geçin",
                            Description = "Butik üretim anlayışı ile size özel mutfak ve banyo çözümleri.",
                            ImageUrl = "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1920&q=80",
                            IsActive = true,
                            Order = 3,
                            Subtitle = "Hayalleriniz, Bizim İşimiz",
                            Title = "Modern ve Zamansız Tasarımlar"
                        });
                });

            modelBuilder.Entity("Onus.API.Models.PageContent", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ContentKey")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ContentValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Page")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Section")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("PageContents");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ContentKey = "title",
                            ContentValue = "Projeniz İçin Ücretsiz Teklif Alın",
                            Page = "home",
                            Section = "cta"
                        },
                        new
                        {
                            Id = 2,
                            ContentKey = "description",
                            ContentValue = "Uzman ekibimiz hayallerinizdeki mutfak ve banyo tasarımını gerçeğe dönüştürmeye hazır. Hemen iletişime geçin, ücretsiz keşif ve teklif hizmetinden faydalanın.",
                            Page = "home",
                            Section = "cta"
                        },
                        new
                        {
                            Id = 3,
                            ContentKey = "buttonText",
                            ContentValue = "İletişime Geçin",
                            Page = "home",
                            Section = "cta"
                        },
                        new
                        {
                            Id = 4,
                            ContentKey = "buttonLink",
                            ContentValue = "/iletisim",
                            Page = "home",
                            Section = "cta"
                        },
                        new
                        {
                            Id = 5,
                            ContentKey = "description",
                            ContentValue = "Doğanın çırağı, ahşabın ustası. ONUS Mutfak & Banyo olarak özel tasarım mutfak ve banyo çözümleri sunuyoruz.",
                            Page = "footer",
                            Section = "main"
                        },
                        new
                        {
                            Id = 6,
                            ContentKey = "address",
                            ContentValue = "İstanbul, Türkiye",
                            Page = "footer",
                            Section = "main"
                        },
                        new
                        {
                            Id = 7,
                            ContentKey = "phone",
                            ContentValue = "+90 555 555 55 55",
                            Page = "footer",
                            Section = "main"
                        },
                        new
                        {
                            Id = 8,
                            ContentKey = "email",
                            ContentValue = "info@onus.com.tr",
                            Page = "footer",
                            Section = "main"
                        },
                        new
                        {
                            Id = 9,
                            ContentKey = "title",
                            ContentValue = "Hakkımızda",
                            Page = "about",
                            Section = "hero"
                        },
                        new
                        {
                            Id = 10,
                            ContentKey = "subtitle",
                            ContentValue = "Doğanın Çırağı, Ahşabın Ustası",
                            Page = "about",
                            Section = "hero"
                        },
                        new
                        {
                            Id = 11,
                            ContentKey = "mainText",
                            ContentValue = "ONUS Mutfak & Banyo olarak 15 yılı aşkın süredir, doğal ahşabın sıcaklığını modern tasarımla buluşturarak hayallerinizdeki mekanları yaratıyoruz. Butik üretim anlayışımız ile her projeye özel çözümler sunuyor, el işçiliğinde mükemmelliği hedefliyoruz.",
                            Page = "about",
                            Section = "content"
                        });
                });

            modelBuilder.Entity("Onus.API.Models.Project", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Details")
                        .HasColumnType("text");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.ToTable("Projects");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Category = "Mutfak",
                            CreatedDate = new DateTime(2025, 12, 8, 9, 39, 54, 92, DateTimeKind.Utc).AddTicks(8852),
                            Description = "Minimal ve fonksiyonel mutfak çözümü",
                            Details = "Bu projede açık mutfak konsepti ile salon birleştirildi.",
                            ImageUrl = "https://images.unsplash.com/photo-1556911220-bff31c812dba?auto=format&fit=crop&w=800&q=80",
                            IsActive = true,
                            Title = "Modern Mutfak Tasarımı"
                        },
                        new
                        {
                            Id = 2,
                            Category = "Banyo",
                            CreatedDate = new DateTime(2025, 12, 8, 9, 39, 54, 92, DateTimeKind.Utc).AddTicks(8854),
                            Description = "Spa konseptli modern banyo tasarımı",
                            Details = "Doğal taş kaplama ve özel aydınlatma ile spa atmosferi yaratıldı.",
                            ImageUrl = "https://images.unsplash.com/photo-1552321554-5fefe8c9ef14?auto=format&fit=crop&w=800&q=80",
                            IsActive = true,
                            Title = "Lüks Banyo Projesi"
                        });
                });

            modelBuilder.Entity("Onus.API.Models.Reference", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("CompanyName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Industry")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Logo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.ToTable("References");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CompanyName = "Hilton Hotels",
                            Description = "5 yıldızlı otel mutfak ve banyo tadilat projesi",
                            Industry = "Otelcilik",
                            Logo = "https://upload.wikimedia.org/wikipedia/commons/4/44/Hilton_Worldwide_Logo.svg",
                            Website = "https://www.hilton.com",
                            Year = 2023
                        },
                        new
                        {
                            Id = 2,
                            CompanyName = "Starbucks",
                            Description = "Cafe mobilya ve dekorasyon projeleri",
                            Industry = "Restoran",
                            Logo = "https://upload.wikimedia.org/wikipedia/en/d/d3/Starbucks_Corporation_Logo_2011.svg",
                            Website = "https://www.starbucks.com",
                            Year = 2024
                        },
                        new
                        {
                            Id = 3,
                            CompanyName = "Mercedes-Benz",
                            Description = "Showroom ve ofis iç mekan projesi",
                            Industry = "Otomotiv",
                            Logo = "https://upload.wikimedia.org/wikipedia/commons/9/90/Mercedes-Logo.svg",
                            Website = "https://www.mercedes-benz.com",
                            Year = 2023
                        });
                });

            modelBuilder.Entity("Onus.API.Models.SiteSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FacebookUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("InstagramUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("SiteName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("WhatsAppNumber")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("SiteSettings");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Address = "Doğanın Çırağı, Ahşabın Ustası\nİstanbul, Türkiye",
                            Email = "info@onus.com.tr",
                            FacebookUrl = "https://facebook.com",
                            InstagramUrl = "https://instagram.com",
                            Phone = "+90 555 555 55 55",
                            SiteName = "ONUS Mutfak & Banyo",
                            UpdatedDate = new DateTime(2025, 12, 8, 9, 39, 54, 92, DateTimeKind.Utc).AddTicks(8626),
                            WhatsAppNumber = "+905555555555"
                        });
                });

            modelBuilder.Entity("Onus.API.Models.Statistic", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Order")
                        .HasColumnType("integer");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Statistics");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Icon = "CheckCircle",
                            Order = 1,
                            Title = "Tamamlanan Proje",
                            Value = "500+"
                        },
                        new
                        {
                            Id = 2,
                            Icon = "Heart",
                            Order = 2,
                            Title = "Mutlu Müşteri",
                            Value = "98%"
                        },
                        new
                        {
                            Id = 3,
                            Icon = "Award",
                            Order = 3,
                            Title = "Yıllık Deneyim",
                            Value = "15+"
                        },
                        new
                        {
                            Id = 4,
                            Icon = "Users",
                            Order = 4,
                            Title = "Uzman Ekip",
                            Value = "25+"
                        });
                });

            modelBuilder.Entity("Onus.API.Models.Testimonial", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("IsApproved")
                        .HasColumnType("boolean");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Rating")
                        .HasColumnType("integer");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Testimonials");
                });

            modelBuilder.Entity("Onus.API.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime?>("LastLoginDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedDate = new DateTime(2025, 12, 8, 9, 39, 54, 92, DateTimeKind.Utc).AddTicks(8820),
                            Email = "admin@onus.com.tr",
                            PasswordHash = "$2a$11$8ZqrDdGvEF.YzCnJ5RqWy.vKJ4Zxh5LqXk9Kx8JYxJz5Kz8JYxJz5K",
                            Role = "Admin",
                            Username = "admin"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
